import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "react-toastify/dist/ReactToastify.css";
import { Toaster } from "react-hot-toast";
import NextThemeProvider from "@/providers/NextThemeProvider";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Petyfy",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="bg-background text-foreground min-h-full flex flex-col w-10/12 mx-auto">
                <NextThemeProvider>
                    <Navbar></Navbar>
                    <main>{children}</main>
                    <Footer></Footer>
                    <Toaster></Toaster>
                </NextThemeProvider>
            </body>
        </html>
    );
}
